### ISSUE TITLE
Is this repo up to date?

### ISSUE THREAD

**Issue by gianpaj** [ion-book/tinderforx#1]
Just asking because on Ionic Market it says "updated 4 days ago" (24 March):
http://market.ionic.io/starters/astinderforx

**Comment by carlosrojaso** [comment]
Hi @gianpaj thank you for comment. I guess that the update date in Ionic Market is from when i modify the info in the Market :p But with the last  commit this seems working ok w/ Ionic 1.2.x. Let me know if you find issues ;)
