### ISSUE TITLE
Firebase configuration missing

### ISSUE THREAD

**Issue by harpreet2602** [ion-book/tinderforx#6]
Under the installation steps here: http://market.ionic.io/starters/astinderforx, it says about the firebase configuration in app.js but the code is missing. Can you please check ? 

Also, this is ionic v1 project, do you have the code for ionic v2

**Comment by carlosrojaso** [comment]
Hi this is because the free version is outdated and without firebase integration. for the new version go here: https://gumroad.com/l/DvgQF
